sonar.projectKey=tranhathu07_Helmet-Detection
sonar.organization=tranhathu07

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=Helmet-Detection
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=Backend_API,Helmet_Detection,IoT_hand_gestures

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8